### ISSUE TITLE
Set a default role for users

### ISSUE THREAD

**Issue by vbrown608** [squiggy/eff_fab#20]
Example: https://github.com/plataformatec/devise/wiki/How-To:-Add-a-default-role-to-a-User

(Otherwise users without roles cause an error when deciding whether to display admin functionality)

**Comment by vbrown608** [comment]
actually, it looks like that's already implemented! exploring the source of the error further.

**Comment by vbrown608** [comment]
ah okay, the problem was actually that current_user may not be defined now that we anonymous users. added an additional check for that.

**Comment by TheNotary** [comment]
do yo have a PR yet?

Me and Squiggy can patch it quick by using .try or something

**Comment by TheNotary** [comment]
we fixed it
