### ISSUE TITLE
Team ordering....hmmm....

### ISSUE THREAD

**Issue by TheNotary** [squiggy/eff_fab#27]
- We think BW said group like "tech-like" and "legal-like"

**Comment by TheNotary** [comment]
It might be nice to have a script that set's the weights of the team to w/e we decide is ideal.

**Comment by vbrown608** [comment]
The current weights are based on https://etherpad.eff.org/p/R9SRzU8ver

**Comment by vbrown608** [comment]
(by current I mean defined in seeds.rb)

**Comment by TheNotary** [comment]
Where are orders set?

Let's move Executive to the bottom.  

'''
Cluster techops, techproj, webdev. 
Cluster press and design. International near activism. 
Civlib and IP together. Intake below civlib and IP. 
Finance and development together. Operations after that. 
Exec team last.
'''

**Comment by TheNotary** [comment]
solved
